# Dependencies
markdown:         kramdown #redcarpet
highlighter:      rouge
gems:
- jekyll-paginate
- jekyll-gist
# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            run and startup
tagline:          'a blog about run and startup'
description:      'Talk about something about running & startup'
url:              http://rundupio.github.io
baseurl:          /
disqusid:	  'kkZlT5tYIYCm'

author:
  name:           'rundupio'
  url:            https://github.com/rundupio

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/rundupio
